<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Castle Windsor para IoC y DynamicProxy para AOP -->
  <ItemGroup>
    <PackageReference Include="Castle.Windsor" Version="6.0.0" />
    <PackageReference Include="Castle.Core" Version="5.1.1" />
  </ItemGroup>

</Project>
